"""init

Revision ID: 4115e23a03b8
Revises:
Create Date: 2024-06-07 15:38:21.883253

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4115e23a03b8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sample_models",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sample_models_id"), "sample_models", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sample_models_id"), table_name="sample_models")
    op.drop_table("sample_models")
    # ### end Alembic commands ###
